command_line:
    io:
        input_driver_service: 'cli.abstract.bash_input_driver'
        output_driver_service: 'cli.abstract.bash_output_driver'
        arguments_container_service: 'cli.abstract.arguments_container'
        output_formatters:
            - {service: 'cli.output_formatter.shortcodes'}
    commands:
        service: 'cli.commander'
        parent_tag: 'cli.command'
        child_tag: 'cli.child_command'